import mongoose from 'mongoose';

const videoSchema = new mongoose.Schema({
    moduleId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Module',
        required: true,
        index: true
    },
    title: {
        type: String,
        required: true,
        trim: true
    },
    r2Path: {
        type: String,
        required: true,
        trim: true
    },
    duration: {
        type: Number, // Seconds
        default: 0
    },
    orderIndex: {
        type: Number,
        required: true,
        index: true
    },
    isFreePreview: {
        type: Boolean,
        default: false,
        index: true
    },
    active: {
        type: Boolean,
        default: true,
        index: true
    },
    // SECURE RESOURCES (Atomic Unit)
    resources: [{
        // _id is automatically generated by Mongoose
        title: { type: String, required: true },
        type: { type: String, enum: ['pdf', 'ebook'], required: true },
        r2Path: { type: String, required: true } // Private R2 path (e.g., courses/123/notes.pdf)
    }],
    // Playlist support (multi-part videos)
    parts: [{
        title: { type: String, required: true },
        r2Path: { type: String, required: true },
        duration: { type: Number, default: 0 },
        orderIndex: { type: Number, required: true },
        publishDate: { type: Date, default: Date.now },
        author: { type: String, default: 'AstroBharat' }
    }]
}, {
    timestamps: true
});

// Compound index for ordering within a module
videoSchema.index({ moduleId: 1, orderIndex: 1 });

export default mongoose.model('Video', videoSchema);
