import express from 'express';
import Course from '../models/Course.js';
import { requireAdmin } from '../middleware/adminAuth.js';
import { requirePermission } from '../middleware/permissions.js';

const router = express.Router();

/**
 * GET /api/admin/courses
 * List all courses with filtering and pagination
 */
router.get('/', requireAdmin, requirePermission('courses.view'), async (req, res) => {
    try {
        const {
            page = 1,
            limit = 20,
            status,
            category,
            accessType,
            search
        } = req.query;

        // Build filter
        const filter = {};
        if (status) filter.status = status;
        if (category) filter.category = category;
        if (accessType) filter.accessType = accessType;
        if (search) {
            filter.$or = [
                { title: { $regex: search, $options: 'i' } },
                { description: { $regex: search, $options: 'i' } }
            ];
        }

        // Execute query with pagination
        const skip = (page - 1) * limit;
        const courses = await Course.find(filter)
            .populate('createdBy', 'name email')
            .populate('updatedBy', 'name email')
            .sort({ orderIndex: 1, createdAt: -1 })
            .skip(skip)
            .limit(parseInt(limit));

        const total = await Course.countDocuments(filter);

        res.json({
            success: true,
            data: courses,
            pagination: {
                page: parseInt(page),
                limit: parseInt(limit),
                total,
                pages: Math.ceil(total / limit)
            }
        });
    } catch (error) {
        console.error('List courses error:', error);
        res.status(500).json({ success: false, error: 'Failed to fetch courses' });
    }
});

/**
 * GET /api/admin/courses/:id
 * Get single course by ID
 */
router.get('/:id', requireAdmin, requirePermission('courses.view'), async (req, res) => {
    try {
        const course = await Course.findById(req.params.id)
            .populate('createdBy', 'name email')
            .populate('updatedBy', 'name email');

        if (!course) {
            return res.status(404).json({ success: false, error: 'Course not found' });
        }

        res.json({ success: true, data: course });
    } catch (error) {
        console.error('Get course error:', error);
        res.status(500).json({ success: false, error: 'Failed to fetch course' });
    }
});

/**
 * POST /api/admin/courses
 * Create new course
 */
router.post('/', requireAdmin, requirePermission('courses.create'), async (req, res) => {
    try {
        const courseData = {
            ...req.body,
            createdBy: req.user._id,
            updatedBy: req.user._id
        };

        // Slug will be auto-generated by pre-save hook if not provided
        const course = await Course.create(courseData);

        res.status(201).json({
            success: true,
            data: course,
            message: 'Course created successfully'
        });
    } catch (error) {
        console.error('Create course error:', error);
        res.status(500).json({
            success: false,
            error: error.message || 'Failed to create course'
        });
    }
});

/**
 * PUT /api/admin/courses/:id
 * Update course
 */
router.put('/:id', requireAdmin, requirePermission('courses.edit'), async (req, res) => {
    try {
        const oldCourse = await Course.findById(req.params.id);
        if (!oldCourse) {
            return res.status(404).json({ success: false, error: 'Course not found' });
        }

        const updateData = {
            ...req.body,
            updatedBy: req.user._id
        };

        const course = await Course.findByIdAndUpdate(
            req.params.id,
            updateData,
            { new: true, runValidators: true }
        );

        res.json({
            success: true,
            data: course,
            message: 'Course updated successfully'
        });
    } catch (error) {
        console.error('Update course error:', error);
        res.status(500).json({ success: false, error: 'Failed to update course' });
    }
});

/**
 * DELETE /api/admin/courses/:id
 * Delete course
 */
router.delete('/:id', requireAdmin, requirePermission('courses.delete'), async (req, res) => {
    try {
        const course = await Course.findById(req.params.id);
        if (!course) {
            return res.status(404).json({ success: false, error: 'Course not found' });
        }

        await Course.findByIdAndDelete(req.params.id);

        res.json({
            success: true,
            message: 'Course deleted successfully'
        });
    } catch (error) {
        console.error('Delete course error:', error);
        res.status(500).json({ success: false, error: 'Failed to delete course' });
    }
});

/**
 * PATCH /api/admin/courses/:id/publish
 * Toggle course publish status
 */
router.patch('/:id/publish', requireAdmin, requirePermission('courses.edit'), async (req, res) => {
    try {
        const course = await Course.findById(req.params.id);
        if (!course) {
            return res.status(404).json({ success: false, error: 'Course not found' });
        }

        const newStatus = course.status === 'published' ? 'draft' : 'published';
        course.status = newStatus;
        if (newStatus === 'published') {
            course.publishedAt = new Date();
        }
        course.updatedBy = req.user._id;
        await course.save();

        res.json({
            success: true,
            data: course,
            message: `Course ${newStatus === 'published' ? 'published' : 'unpublished'} successfully`
        });
    } catch (error) {
        console.error('Toggle publish error:', error);
        res.status(500).json({ success: false, error: 'Failed to update course status' });
    }
});

/**
 * PATCH /api/admin/courses/:id/access-type
 * Toggle course access type (free/paid)
 */
router.patch('/:id/access-type', requireAdmin, requirePermission('courses.edit'), async (req, res) => {
    try {
        const { accessType } = req.body;

        if (!['free', 'paid'].includes(accessType)) {
            return res.status(400).json({ success: false, error: 'Invalid access type' });
        }

        const course = await Course.findById(req.params.id);
        if (!course) {
            return res.status(404).json({ success: false, error: 'Course not found' });
        }

        course.accessType = accessType;
        if (accessType === 'free') {
            course.price = 0;
        }
        course.updatedBy = req.user._id;
        await course.save();

        res.json({
            success: true,
            data: course,
            message: `Course set to ${accessType}`
        });
    } catch (error) {
        console.error('Update access type error:', error);
        res.status(500).json({ success: false, error: 'Failed to update access type' });
    }
});

/**
 * POST /api/admin/courses/bulk-reorder
 * Bulk update course order
 */
router.post('/bulk-reorder', requireAdmin, requirePermission('courses.edit'), async (req, res) => {
    try {
        const { orders } = req.body; // [{ id, orderIndex }]

        const bulkOps = orders.map(({ id, orderIndex }) => ({
            updateOne: {
                filter: { _id: id },
                update: { orderIndex, updatedBy: req.user._id }
            }
        }));

        await Course.bulkWrite(bulkOps);

        res.json({
            success: true,
            message: `${orders.length} courses reordered successfully`
        });
    } catch (error) {
        console.error('Bulk reorder error:', error);
        res.status(500).json({ success: false, error: 'Failed to reorder courses' });
    }
});

export default router;
